//API-1
GET http://localhost:3000/todos/?status=TO%20DO
###
GET http://localhost:3000/todos/?priority=HIGH
###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###
GET http://localhost:3000/todos/?search_q=Play

###API-2-Returns a specific todo based on the todo ID
GET http://localhost:3000/todos/10/

###API-3-Create a todo in the todo table
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###API-4-Updates the details of a specific todo based on the todo ID

PUT http://localhost:3000/todos/10/
Content-Type: application/json

{ "todo": "Some task" }

###API-5-Deletes a todo from the todo table based on the todo ID
DELETE http://localhost:3000/todos/10/
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
